//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingProject.Migrations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201912170107180_AddCarContextMigration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _201912170107180_AddCarContextMigration() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParkingProject.Migrations.201912170107180_AddCarContextMigration", typeof(_201912170107180_AddCarContextMigration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на H4sIAAAAAAAEAM1Y224bNxB9L9B/WOxTCjiiLy+tsUrgSHYhNLYMr5P30e5IZsMltyTXkL6tD/2k/kKHe79IluQkReAXazhz5sKZw5H+/fuf4P06Ed4zasOVHPtno1PfQxmpmMvV2M/s8u2v/vt3P/8UXMfJ2vtc6V04PbKUZuw/WZteMmaiJ0zAjBIeaWXU0o4ilTCIFTs/Pf2NnZ0xJAifsDwveMik5QnmH+jjRMkIU5uBuFUxClPK6STMUb07SNCkEOHYvwf9hYK71+pPjOyoMPC9K8GBgglRLH0PpFQWLIV6+clgaLWSqzAlAYjHTYqktwRhsEzhslE/NJvTc5cNawwrqCgzViVHAp5dlOVhffNXFdmvy0cFvKZC243LOi/i2J+A9r2+n8uJ0E5nR3lHZHTidY9O6m6gpnF/J94kEzbTOJaYWQ2CLLKF4NEfuHlUX1COZSZEOzgKj846AhIRforabh5wWYY8m/oe69qxvmFt1rIpMppJe3Hue3fk [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
